on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # 権限設定
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v6
      - name: Build - Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        env:
          TZ: 'Asia/Tokyo'
        with:
          root_file: main.tex
          args: -file-line-error -halt-on-error -interaction=nonstopmode
      - name: Rename PDF file
        run: |
          REPO_NAME="${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}"
          TAG_NAME="${GITHUB_REF_NAME}"
          
          ARCHIVE_NAME="${REPO_NAME}-${TAG_NAME}.pdf"
          mv main.pdf $ARCHIVE_NAME
          
          echo "ARTIFACT_NAME=${ARCHIVE_NAME}" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            ${{ env.ARTIFACT_NAME }}